### ISSUE TITLE
Login failed, you have to log in Safari

### ISSUE THREAD

**Issue by gatezh** [goooseman/Torrent-Updater#2]
I am logged in, but still have this error and can't add anything to a watchlist.
El Capitan 10.11.6

**Comment by goooseman** [comment]
Apple changed the way the programs works with cookies and it broke down the app.
Unfortunately, I no longer maintain the app and don't use it myself.
I'm sure I was fixing the bug with the cookies after El Capitan release, but now it doesn't work even for me. Maybe smth was changed one more time.

Maybe one day I will find some time during a cup of coffee to find the problem, but can't really promise nothing.

If you can fix the problem (or knows somebody who can), will be happy to receive a pull request and rebuild a new version of the program.

**Comment by goooseman** [comment]
@gatezh Hi, found some time on the weekend. The issue with login was only that rutracker.org is https now, so the url has changed to https://rutracker.org.

I have fixed the problem, changed the parser settings for RuTracker.org.

There is only one issue left with this tracker: download doesn't work and I don't have any time to cope with this problem. 

Anyway, adding and updating the torrents fork for now.

**Comment by goooseman** [comment]
@gatezh released new version, you can check for updates in the About menu

**Comment by gatezh** [comment]
That was the most critical part - to track for updates.
Thank you!
